import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    titleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        marginBottom: 8,
        paddingTop: 8,
    },
    totalText: {
        fontSize: 20,
        fontWeight: '700',
        color: '#2A9D8F',
        marginBottom: 4,
    },
    itemCount: {
        fontSize: 14,
        color: '#666',
    },
    emptyContainer: {
        width: '100%',
        padding: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyText: {
        fontSize: 18,
        marginTop: 16,
        marginBottom: 4,
        textAlign: 'center',
        color: '#333',
    },
    emptySubtext: {
        fontSize: 14,
        color: '#888',
        textAlign: 'center',
    },
    productsContainer: {
        paddingTop: 8,
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    productCard: {
        borderRadius: 16,
        padding: 16,
        marginBottom: 20,
        width: '48%',
        height: 390,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'space-between',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
        borderWidth: 1,
        borderColor: '#F0F0F0',
    },
    imageContainer: {
        width: '100%',
        height: 120,
        marginBottom: 12,
        borderRadius: 8,
        overflow: 'hidden',
        justifyContent: 'center',
        alignItems: 'center',
    },
    productImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'contain',
    },
    productTitle: {
        fontWeight: '600',
        fontSize: 16,
        marginBottom: 4,
        textAlign: 'center',
        color: '#333',
    },
    productCategory: {
        fontSize: 12,
        color: '#888',
        marginBottom: 8,
        textAlign: 'center',
        textTransform: 'capitalize',
    },
    productPrice: {
        fontWeight: 'bold',
        fontSize: 18,
        color: '#2A9D8F',
        textAlign: 'center',
        marginBottom: 12,
    },
    quantityControls: {
        width: '100%',
        marginTop: 8,
    },
    quantityContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 12,
    },
    quantityButton: {
        backgroundColor: '#F5F5F5',
        borderRadius: 20,
        width: 32,
        height: 32,
        justifyContent: 'center',
        alignItems: 'center',
        marginHorizontal: 8,
    },
    quantityText: {
        fontSize: 16,
        fontWeight: '600',
        minWidth: 20,
        textAlign: 'center',
    },
    deleteButton: {
        flexDirection: 'row',
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        gap: 8,
    },
    deleteButtonText: {
        color: '#F44336',
        fontWeight: '600',
        fontSize: 14,
    },
    buttonPressed: {
        opacity: 0.8,
        transform: [{ scale: 0.98 }],
    },
    reactLogo: {
        height: "100%",
        width: "100%",
    },
});