import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    titleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        marginBottom: 16,
    },
    reactLogo: {
        height: "100%",
        width: "100%",
    },
    searchContainer: {
        marginBottom: 20,
        width: '100%',
    },
    searchInput: {
        width: '100%',
        color: 'rgba(71, 69, 36, 0.2)3',
        height: 50,
        paddingHorizontal: 16,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#E0E0E0',
        fontSize: 16,
    },
    productsContainer: {
        paddingTop: 8,
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 40,
    },
    loadingText: {
        marginTop: 16,
        fontSize: 16,
        color: '#666',
    },
    emptyContainer: {
        width: '100%',
        padding: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyText: {
        fontSize: 18,
        marginBottom: 8,
        textAlign: 'center',
    },
    productCard: {
        borderRadius: 16,
        padding: 16,
        marginBottom: 20,
        width: '48%',
        height: 300,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'space-between',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
        borderWidth: 1,
        borderColor: '#F0F0F0',
    },
    imageContainer: {
        width: '100%',
        height: 100,
        marginBottom: 12,
        borderRadius: 8,
        overflow: 'hidden',
        justifyContent: 'center',
        alignItems: 'center',
    },
    productImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'contain',
    },
    productTitle: {
        fontWeight: '600',
        fontSize: 14,
        marginBottom: 4,
        textAlign: 'center',
    },
    productCategory: {
        fontSize: 12,
        color: '#888',
        marginBottom: 8,
        textAlign: 'center',
        textTransform: 'capitalize',
    },
    productPrice: {
        fontWeight: 'bold',
        fontSize: 16,
        color: '#2A9D8F',
        textAlign: 'center',
    },
    addButton: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 16,
        borderWidth: 1,
        borderColor: '#fcd200',
        borderRadius: 6,
        width: 130,
        height: 48,
        paddingVertical: 12,
        paddingHorizontal: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    buttonPressed: {
        backgroundColor: '#f7ca00',
    },
    buttonText: {
        fontSize: 14,
        textAlign: 'center',
        fontWeight: '600',
    },

    searchButton: {
        flexDirection: 'row',
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        gap: 8,
    },
    searchButtonText: {
        color: '#F44336',
        fontWeight: '600',
        fontSize: 14,
    },
});